version: '3'
services:
  miau-whatspam:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
      - ./media:/app/media
      - ./history:/app/history
      - ./db:/app/db
    #command: sleep infinity
    command: ["/app/miau-whatspam"]
